# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: dev
    init: |
      cd /workspace/How-to-implement-a-wizard-in-React
      npm install
    command: |
      cd /workspace/How-to-implement-a-wizard-in-React
      npm start

ports:
  - port: 3000
    onOpen: ignore

vscode:
  extensions:
    # Spell checker
    - streetsidesoftware.code-spell-checker
